name:                haskell-aoc
version:             0.1.0.0
github:              "MisterPeModder/haskell-aoc"
license:             Apache-2.0
author:              "MisterPeModder"
maintainer:          "yguaye@gmail.com"
copyright:           "2021 Yanis Guaye"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/MisterPeModder/haskell-aoc#readme>

dependencies:
- base >= 4.7 && < 5
- exceptions
- http-conduit >= 2.3.8
- bytestring
- text
- http-types
- aeson >= 2.0.2.0
- directory
- transformers

library:
  source-dirs: src

executables:
  haskell-aoc-exe:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-aoc

tests:
  haskell-aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-aoc
